name: Node.js Batch Runner

on:
  workflow_dispatch:
  schedule:
    - cron: '5 5 * * *'

jobs:
  build-and-run:
    runs-on: ubuntu-20.04

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3

    - name: Install dependencies
      run: npm install
      working-directory: app

    - name: Run index.js
      run: node index.js
      working-directory: app
      env:
        AUTHOR: ${{ secrets.AUTHOR }}
        PASSWORD: ${{ secrets.PASSWORD }}
